import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#F6F7F9" },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  tituloHeader: { flex: 1, fontSize: 17, fontWeight: "800", color: "#0F172A" },
  botao: {
    width: 36,
    height: 36,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    alignItems: "center",
    justifyContent: "center",
  },
  content: { padding: 16, paddingBottom: 32 },
  title: { fontSize: 30, fontWeight: "800", color: "#0F172A" },
  subtitle: { fontSize: 15, color: "#6B7280", marginTop: 6, marginBottom: 20 },
  erroBox: {
    padding: 12,
    borderRadius: 10,
    backgroundColor: "#FEF2F2",
    marginBottom: 16,
  },
  erro: { color: "#B91C1C" },
  tentar: { marginTop: 8, color: "#EA580C", fontWeight: "700" },
  painel: {
    backgroundColor: "#fff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    padding: 16,
    marginBottom: 16,
  },
  painelTituloLinha: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  painelTitulo: { flex: 1, fontSize: 16, fontWeight: "800", color: "#0F172A" },
  contador: {
    minWidth: 28,
    textAlign: "center",
    paddingVertical: 4,
    borderRadius: 12,
    backgroundColor: "#F1F5F9",
    color: "#334155",
    fontWeight: "700",
  },
  vazio: { textAlign: "center", color: "#9CA3AF", paddingVertical: 8 },
  pedido: { paddingVertical: 12, borderTopWidth: 1, borderTopColor: "#F3F4F6" },
  pedidoTitulo: { fontWeight: "800", color: "#111827" },
  pedidoDestino: { marginTop: 3, fontWeight: "600", color: "#EA580C" },
  pedidoItens: { marginTop: 4, color: "#6B7280", lineHeight: 19 },
});
